version: '3'

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: lamp_demo
            MYSQL_USER: lamp_demo
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql:/var/lib/mysql

    www:
        depends_on:
            - db    
        image: php:8.1.1-apache
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin

