version: '3'

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: lamp_demo
            MYSQL_USER: lamp_demo
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql:/var/lib/mysql

    www:
        depends_on:
            - db    
        image: php:8.1.1-apache
        volumes:
            - "./:/var/www/html"
        ports:
            - 80:80
            - 443:443

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306

